name: CarnellCodyBridges
favicon: null
layout_spectrum: 0.7938523872289807
typography_spectrum: 0.8921041376888752
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3790569144766778
  lightness: 0.5120617733336985
  saturation: 0.876534387236461
  rhythmicContrast: 0.9001504010520875
purpose: []
