name: CarnellCodyBridges
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: 'Lifetime Member #1234567890#14423424567890#14,424,659,135,780...'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff0000'
    - '#ff7f00'
    - '#ffff00'
    - '#00bc3f'
    - '#0068ff'
  brandStrength: 1
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
